### ISSUE TITLE
[bug #34560] math.h error while compiling

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#494]
Sun 16 Oct 2011 01:32:19 AM CEST

The error below appeared after updating from Kubuntu 11.04 to 11.10. This went from AVR version 1.6.7 to 1.7.1. The error itself happened while compiling code in the Arduino 0022 IDE. It made no difference what code I compiled I get this error every time.

In file included from /usr/lib/gcc/avr/4.5.3/../../../avr/include/util/delay.h:44:0,
from /usr/lib/gcc/avr/4.5.3/../../../avr/include/avr/delay.h:37,
from /opt/arduino-0022/hardware/arduino/cores/arduino/wiring_private.h:30,
from /opt/arduino-0022/hardware/arduino/cores/arduino/WInterrupts.c:34:
/usr/lib/gcc/avr/4.5.3/../../../avr/include/math.h:426:15: error: expected identifier or ‘(’ before ‘double’
/usr/lib/gcc/avr/4.5.3/../../../avr/include/math.h:426:15: error: expected ‘)’ before ‘>=’ token

This issue was migrated from https://savannah.nongnu.org/bugs/?34560

**Comment by avrs-admin** [comment]
Georg-Johann Lay <gjlayde>
Sun 16 Oct 2011 02:47:42 AM CEST

math.h's line #462 is the end of the file and empty.

Thus math.h:426:15 is no part of math.h and the error message might be misleading because of fuzzyness in compiler location tracking and just as well point to some other header or your source.

Generate a preprocessed output (.i/.ii generated with -save-temps) and attach it.

**Comment by avrs-admin** [comment]
Carl John Nobile <cnobile>
Sun 16 Oct 2011 07:00:50 AM CEST

I know it is not my source since it works perfectly well with the older version of AVR and all of the Arduino examples I tried failed wite the exact same error.

Since I got this error with the Arduino IDE how would I generate a preprocessed output outside of the IDE?

**Comment by avrs-admin** [comment]
Georg-Johann Lay <gjlayde>
Sun 16 Oct 2011 12:39:55 PM CEST

It's problem in Arduino header, see

[http://www.avrfreaks.net/index.php?name=PNphpBB2&file=viewtopic&p=870506#870506](https://savannah.nongnu.orghttp://www.avrfreaks.net/index.php?name=PNphpBB2&file=viewtopic&p=870506#870506)

**Comment by avrs-admin** [comment]
Joerg Wunsch <joerg_wunsch>
Sun 16 Oct 2011 03:19:40 PM CEST

Not only a `problem' but a bug, actually.  "round", being
part of the standard library, belongs to the implementation
namespace and thus must not be defined by an application.
