### ISSUE TITLE
[bug #27201] _WORDREGISTER in xmega headers does not work in C99 mode

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avr-libc#392]
Fri 07 Aug 2009 12:41:28 PM CEST

When using -std=c99 in conjunction with ATxmega128A1 the following example code from the website for Xmega (Application node AVR1300: Using the XMEGA ADC) does not compile for avr-gcc (Win-AVR20090313).

ADC_CH_t *acd_ch;
int16_t answer;
answer = adc_ch->RES;

This creates the following error message:
"error: 'ADC_CH_t' has no member named 'RES'

When looking at the corresponding header file iox128a1.h the type ADC_CH_t is defined as such:

typedef struct ADC_CH_struct
{
register8_t CTRL;  /* Control Register */
register8_t MUXCTRL;  /* MUX Control */
register8_t INTCTRL;  /* Channel Interrupt Control */
register8_t INTFLAGS;  /* Interrupt Flags */
_WORDREGISTER(RES);  /* Channel Result */
register8_t reserved_0x6;
register8_t reserved_0x7;
} ADC_CH_t;

The issue is caused be the definition of "_WORDREGISTER" in line 94:

#define _WORDREGISTER(regname)   \
union \
{ \
register16_t regname; \
struct \
{ \
register8_t regname ## L; \
register8_t regname ## H; \
}; \
}

This does not work for C99, which (unfortunately) I need for my project.

The code works with IAR Workbench 5.30.02.

[file #18585: bug27201.patch](https://savannah.nongnu.org/bugs/download.php?file_id=18585)
[file #18586: NEWS](https://savannah.nongnu.org/bugs/download.php?file_id=18586)
[file #18587: ChangeLog](https://savannah.nongnu.org/bugs/download.php?file_id=18587)

This issue was migrated from https://savannah.nongnu.org/bugs/?27201

**Comment by avrs-admin** [comment]
Joerg Wunsch <joerg_wunsch>
Fri 07 Aug 2009 12:52:35 PM CEST

The problem is that accessing the union (and also struct,
for byte-wide access) elements without naming the union
itself is a GCC extension, so it is turned off when compiling
with -std=c99.

It appears to me that prepending the entire union declaration
with **_extension_** does fix it by telling GCC "It's OK to use
the following GCC extension here, regardless of the --std
option in effect".

**Comment by avrs-admin** [comment]
Eric Weddington <arcanum>
Tue 01 Sep 2009 01:49:09 AM CEST

Ok, finally committed.
